# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that installs and configures java-cfenv"
  homepage = "https://github.com/garethjevans/java-cfenv-buildpack"
  id = "garethjevans/java-cfenv-buildpack"
  keywords = ["java", "java-cfenv", "cfenv", "paketo", "buildpacks"]
  name = "Java CFENV Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/garethjevans/java-cfenv-buildpack/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "false"
    description = "enables the buildpack"
    build = true
    name = "BP_JAVA_CFENV_ENABLE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:io.pivotal:java-cfenv:2.4.0:*:*:*:*:*:*:*"]
    id = "java-cfenv"
    name = "java-cfenv"
    purl = "pkg:generic/java-cfenv@2.4.0"
    sha256 = "ee8d3b567e8806a0f16ec8aa7363c9e5857518f75698d18d6e310318e2b002c7"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://repo1.maven.org/maven2/io/pivotal/cfenv/java-cfenv-boot/2.4.0/java-cfenv-boot-2.4.0.jar"
    version = "2.4.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/pivotal-cf/java-cfenv/blob/main/LICENSE"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

